# Generated by Django 4.0.4 on 2022-05-03 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id_timer', models.AutoField(primary_key=True, serialize=False)),
                ('initial_date', models.DateTimeField(default=datetime.datetime.now)),
                ('time_seconds', models.IntegerField(default=0)),
                ('end_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Timer',
                'verbose_name_plural': 'Timers',
                'db_table': 'timer',
                'managed': True,
            },
        ),
    ]
